### ISSUE TITLE
Cube Viewer: Enter in editable cell creates carriage return not progress to next row

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#232]
Arc 1.1.3

This may be related to #231 
Assuming no thousand separators are present in the numeric value hitting tab has the expected behavior that the value is committed and active cell advances one cell to right. However hitting enter the cell retains focus and a carriage return is entered in the cell rather than the value being committed and advancing the active cell one row down.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We have added some extra parsing options so that numbers with comma's are parsed correctly. It is based on default settings of comma for thousands and period for decimals. To switch these settings update `settings.yml` using the parameters below:

```
# Number formats used for passing values in the cube viewer
number:
  precision: 2   # Default number of decimal places
  thousand: ","  # Separator used for thousands
  decimal:  "."  # Separator used for decimals
```
